### ISSUE TITLE
Remove interaction prompts

### ISSUE THREAD

**Issue by pawiecz** [nuclearcat/kci-easy#2]
AIUI this environment is aimed at non-interactive use and possibly staging instance replacement. This requirement forces dropping any prompt for user interaction. This issue will track such occurrences:

`1-rebuild_all.sh`
- [x] https://github.com/nuclearcat/kci-easy/blob/33640ec2f27d5be0f49cad8a35050b56e78a758b/1-rebuild_all.sh#L56

`2-install_api.sh`
- [x] https://github.com/nuclearcat/kci-easy/blob/33640ec2f27d5be0f49cad8a35050b56e78a758b/2-install_api.sh#L45
- [x] https://github.com/nuclearcat/kci-easy/blob/33640ec2f27d5be0f49cad8a35050b56e78a758b/2-install_api.sh#L49

**Comment by nuclearcat** [comment]
Yes, i am planning to send PR to make 2 last one non-interactive, and for first one likely i will introduce non-interactive option. Thanks for reminding that!

**Comment by pawiecz** [comment]
Right - first should be fine with a simple `-f` suffix, others might require `expect` script (or, more conveniently, `autoexpect`-generated one) as they are password prompts.

**Comment by pawiecz** [comment]
All remaining subtasks have been resolved in #5
